model_name: tinyllama_1_1b_chat_uncensored
base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_family: llama  # if unspecified will use AutoModelForCausalLM/AutoTokenizer
model_context_window: 4096  # if unspecified will use tokenizer.model_max_length
data:
  type: vicuna
  dataset: georgesung/wizard_vicuna_70k_unfiltered  # HuggingFace hub
  user_header: "### HUMAN:\n"
  response_header: "### RESPONSE:\n"
lora:
  r: 8
  lora_alpha: 16
  target_modules:  # modules for which to train lora adapters
  - q_proj
  - k_proj
  - v_proj
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
trainer:
  batch_size: 1
  gradient_accumulation_steps: 4
  warmup_steps: 100
  num_train_epochs: 1
  learning_rate: 0.0002  # 2e-4
  logging_steps: 20
  max_steps: 1000
  optim: "paged_adamw_8bit" # Add this line
trainer_output_dir: trainer_outputs/
model_output_dir: models/  # model saved in {model_output_dir}/{model_name}
